# Generated by Django 4.1.2 on 2023-12-27 11:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_rename_payment_order_payment_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='payment_id',
            new_name='payment',
        ),
    ]
